version: '3'
services:
  fmanage:
    build: .
#    image: tfuruya/fmanage-app:v3
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=fmanage.environment.gke_local
    ports:
      - 9000:8000
    volumes:
      - .:/home/fmanage
  db2:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    volumes:
      - ~/Documents/Local/gcloud/ServiceAccount/cloudsql-client-sa.json:/sa.json
    ports:
      - 5432:5432
    command: [
      "/cloud_sql_proxy",
      "-instances=fmanage-202213:asia-northeast1:cloudsql-fk-management=tcp:0.0.0.0:5432",
      "-credential_file=/sa.json"
    ]
