# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
                ('average_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='holdingstocks',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks'),
        ),
    ]
