# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('commission', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price_line', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('commission', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks')),
            ],
        ),
    ]
