# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20181023_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('order_type', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('commission', models.IntegerField()),
                ('is_nisa', models.BooleanField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyorders',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='sellorders',
            name='stock',
        ),
        migrations.DeleteModel(
            name='BuyOrders',
        ),
        migrations.DeleteModel(
            name='SellOrders',
        ),
    ]
