# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20181023_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
