# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20181113_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
