# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20190510_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexit',
            name='chart_exit',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='date_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='num_exit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='price_exit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='reason_lose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.ReasonLose'),
        ),
    ]
