# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_orders_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='industry',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='market',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
