# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-04 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20190518_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interest_bearing_debt', models.FloatField(blank=True, null=True, verbose_name='有利子負債')),
                ('roa', models.FloatField(blank=True, null=True, verbose_name='ROA')),
                ('roe', models.FloatField(blank=True, null=True, verbose_name='ROE')),
                ('sales', models.FloatField(blank=True, null=True, verbose_name='売上高')),
                ('assets', models.FloatField(blank=True, null=True, verbose_name='総資産')),
                ('eps', models.FloatField(blank=True, null=True, verbose_name='EPS')),
                ('net_income', models.FloatField(blank=True, null=True, verbose_name='当期利益')),
                ('bps', models.FloatField(blank=True, null=True, verbose_name='BPS')),
                ('roa_2', models.FloatField(blank=True, null=True, verbose_name='総資産経常利益率')),
                ('operating_income', models.FloatField(blank=True, null=True, verbose_name='営業利益')),
                ('equity_ratio', models.FloatField(blank=True, null=True, verbose_name='自己資本比率')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='資本金')),
                ('recurring_profit', models.FloatField(blank=True, null=True, verbose_name='経常利益')),
                ('equity', models.FloatField(blank=True, null=True, verbose_name='自己資本')),
                ('pbr_f', models.FloatField(blank=True, null=True, verbose_name='PBR（実績）')),
                ('eps_f', models.FloatField(blank=True, null=True, verbose_name='EPS（会社予想）')),
                ('market_value', models.FloatField(blank=True, null=True, verbose_name='時価総額')),
                ('per_f', models.FloatField(blank=True, null=True, verbose_name='PER（会社予想）')),
                ('dividend_yield', models.FloatField(blank=True, null=True, verbose_name='配当利回り（会社予想）')),
                ('bps_f', models.FloatField(blank=True, null=True, verbose_name='BPS実績')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks')),
            ],
        ),
    ]
