# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20190518_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interest_bearing_debt', models.IntegerField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('assets', models.IntegerField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('net_income', models.IntegerField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('roa_2', models.FloatField(blank=True, null=True)),
                ('operating_income', models.IntegerField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('recurring_profit', models.IntegerField(blank=True, null=True)),
                ('equity', models.IntegerField(blank=True, null=True)),
                ('pbr_f', models.FloatField(blank=True, null=True)),
                ('eps_f', models.FloatField(blank=True, null=True)),
                ('market_value', models.IntegerField(blank=True, null=True)),
                ('per_f', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('bps_f', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Stocks')),
            ],
        ),
    ]
