# Generated by Django 2.2.16 on 2020-10-19 07:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリー名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_category_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_category_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=30, verbose_name='クライアント名')),
                ('client_id', models.CharField(max_length=30, verbose_name='クライアントID')),
                ('is_nonlancers', models.BooleanField(default=False, verbose_name='ランサーズ以外')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_client_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_client_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'クライアント',
                'verbose_name_plural': 'クライアント',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=100, verbose_name='案件名')),
                ('opportunity_id', models.CharField(max_length=30, verbose_name='案件ID')),
                ('description_proposal', models.TextField(verbose_name='提案内容')),
                ('date_proposal', models.DateField(verbose_name='提案日')),
                ('date_proposed_delivery', models.DateField(verbose_name='提案納期')),
                ('val_payment', models.IntegerField(verbose_name='クライアント支払額')),
                ('val', models.IntegerField(verbose_name='報酬額')),
                ('num_proposal', models.IntegerField(verbose_name='提案件数')),
                ('description_opportunity', models.TextField(verbose_name='依頼内容')),
                ('detail_opportunity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='提案詳細（JSON）')),
                ('budget', models.CharField(max_length=20, verbose_name='予算')),
                ('datetime_open_opportunity', models.DateTimeField(verbose_name='依頼開始日時')),
                ('datetime_close_opportunity', models.DateTimeField(verbose_name='依頼締切日時')),
                ('date_desired_delivery', models.DateField(verbose_name='希望納期')),
                ('datetime_updated_opportunity', models.DateTimeField(blank=True, null=True, verbose_name='依頼更新日時')),
                ('status', models.CharField(choices=[('相談中', '相談中'), ('提案中', '提案中'), ('選定/作業中', '選定/作業中'), ('選定/終了', '選定/終了'), ('キャンセル', 'キャンセル'), ('落選', '落選')], max_length=10, verbose_name='ステータス')),
                ('type', models.CharField(choices=[('直接受注', '直接受注'), ('提案受注', '提案受注'), ('追加受注', '追加受注')], max_length=10, verbose_name='タイプ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lancers.Category', verbose_name='カテゴリー')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancers.Client', verbose_name='クライアント')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_opportunity_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_opportunity_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='sub_categories', to='lancers.Category', verbose_name='サブカテゴリー')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
            },
        ),
        migrations.CreateModel(
            name='OpportunityWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('datetime_start', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='終了時間')),
                ('working_time', models.IntegerField(blank=True, null=True, verbose_name='労働時間（分）')),
                ('is_in_calendar', models.BooleanField(default=False, verbose_name='カレンダーへ追加')),
                ('memo', models.TextField(verbose_name='メモ')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_opportunitywork_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_opportunitywork_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancers.Opportunity', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件活動',
                'verbose_name_plural': '案件活動',
            },
        ),
    ]
