# Generated by Django 2.2.16 on 2020-10-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='related_opportunity',
            field=models.ManyToManyField(blank=True, related_name='_opportunity_related_opportunity_+', to='lancers.Opportunity', verbose_name='関連案件'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='date_proposal',
            field=models.DateField(blank=True, null=True, verbose_name='提案日'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='date_proposed_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='提案納期'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_proposal',
            field=models.TextField(blank=True, null=True, verbose_name='提案内容'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='num_proposal',
            field=models.IntegerField(blank=True, null=True, verbose_name='提案件数'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='val',
            field=models.IntegerField(verbose_name='報酬額（税込）'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='val_payment',
            field=models.IntegerField(verbose_name='クライアント支払額（税込）'),
        ),
    ]
