# Generated by Django 2.2.16 on 2020-10-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0002_auto_20201019_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='budget',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='date_desired_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='希望納期'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='datetime_close_opportunity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='依頼締切日時'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='datetime_open_opportunity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='依頼開始日時'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_opportunity',
            field=models.TextField(blank=True, null=True, verbose_name='依頼内容'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='val_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='クライアント支払額（税込）'),
        ),
        migrations.AlterField(
            model_name='opportunitywork',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='opportunitywork',
            name='opportunity',
            field=models.ForeignKey(limit_choices_to={'status__in': ('相談中', '提案中', '選定/作業中'), 'type__in': ('直接受注', '提案受注')}, on_delete=django.db.models.deletion.CASCADE, to='lancers.Opportunity', verbose_name='案件'),
        ),
    ]
