# Generated by Django 2.2.16 on 2020-10-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0003_auto_20201019_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='proposal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='提案ID'),
        ),
    ]
