# Generated by Django 2.2.16 on 2020-10-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0004_opportunity_proposal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='direct_opportunity_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='直接依頼ID'),
        ),
    ]
