# Generated by Django 2.2.16 on 2020-10-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0005_opportunity_direct_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='drive_url',
            field=models.URLField(blank=True, null=True, verbose_name='GoogleDrive'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='knowledge_url',
            field=models.URLField(blank=True, null=True, verbose_name='Knowledge'),
        ),
    ]
