# Generated by Django 2.2.16 on 2020-10-22 01:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0006_auto_20201020_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='detail_opportunity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='依頼詳細（JSON）'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='案件ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='related_opportunity',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type__in': ('直接受注', '提案受注')}, related_name='_opportunity_related_opportunity_+', to='lancers.Opportunity', verbose_name='関連案件'),
        ),
    ]
