# Generated by Django 2.2.16 on 2020-10-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0007_auto_20201022_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='date_close',
            field=models.DateField(blank=True, null=True, verbose_name='案件終了日'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_open',
            field=models.DateField(blank=True, null=True, verbose_name='案件開始日'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='related_opportunity',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='_opportunity_related_opportunity_+', to='lancers.Opportunity', verbose_name='関連案件'),
        ),
    ]
