# Generated by Django 2.2.16 on 2020-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0008_auto_20201026_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='カテゴリー名'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=255, verbose_name='クライアントID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='クライアント名'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='budget',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='direct_opportunity_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='直接依頼ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='案件ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='proposal_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='提案ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('相談中', '相談中'), ('提案中', '提案中'), ('選定/作業中', '選定/作業中'), ('選定/終了', '選定/終了'), ('キャンセル', 'キャンセル'), ('落選', '落選')], max_length=255, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('直接受注', '直接受注'), ('提案受注', '提案受注'), ('追加受注', '追加受注')], max_length=255, verbose_name='タイプ'),
        ),
    ]
