# Generated by Django 2.2.16 on 2020-11-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0010_auto_20201106_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lancers.Client', verbose_name='クライアント'),
        ),
    ]
