# Generated by Django 2.2.16 on 2020-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0011_auto_20201107_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('相談中', '相談中'), ('提案中', '提案中'), ('選定/作業中', '選定/作業中'), ('選定/終了', '選定/終了'), ('キャンセル', 'キャンセル'), ('落選', '落選'), ('別管理', '別管理')], max_length=255, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('直接受注', '直接受注'), ('提案受注', '提案受注'), ('追加受注', '追加受注'), ('MENTA', 'MENTA')], max_length=255, verbose_name='タイプ'),
        ),
    ]
