# Generated by Django 2.2.16 on 2020-12-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0012_auto_20201127_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='opportunitywork',
            name='opportunity',
            field=models.ForeignKey(limit_choices_to={'type__in': ('直接受注', '提案受注', 'MENTA')}, on_delete=django.db.models.deletion.CASCADE, to='lancers.Opportunity', verbose_name='案件'),
        ),
    ]
