# Generated by Django 2.2.16 on 2020-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0013_auto_20201207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='定期案件'),
        ),
    ]
