# Generated by Django 2.2.16 on 2021-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0015_auto_20201229_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('Lancers', 'Lancers'), ('MENTA', 'MENTA'), ('その他', 'その他')], max_length=255, null=True, verbose_name='クライアント種別'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='支払日'),
        ),
    ]
