# Generated by Django 2.2.16 on 2021-02-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lancers', '0016_auto_20210101_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('直接受注', '直接受注'), ('提案受注', '提案受注'), ('追加受注', '追加受注'), ('MENTA', 'MENTA'), ('自己研鑽', '自己研鑽')], max_length=255, verbose_name='タイプ'),
        ),
        migrations.AlterField(
            model_name='opportunitywork',
            name='opportunity',
            field=models.ForeignKey(limit_choices_to={'type__in': ('直接受注', '提案受注', 'MENTA', '自己研鑽')}, on_delete=django.db.models.deletion.CASCADE, to='lancers.Opportunity', verbose_name='案件'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sync_id', models.IntegerField(blank=True, null=True, verbose_name='連携ID')),
                ('name', models.CharField(max_length=256, verbose_name='サービス名')),
                ('opportunity_partern', models.CharField(max_length=256, verbose_name='商談名パターン')),
                ('detail', models.TextField(verbose_name='サービス詳細')),
                ('url', models.URLField(blank=True, null=True, verbose_name='サービスURL')),
                ('val_payment', models.IntegerField(verbose_name='クライアント支払額（税込）')),
                ('is_regular', models.BooleanField(verbose_name='定期案件')),
                ('val', models.IntegerField(verbose_name='報酬額（税込）')),
                ('date_deactivate', models.DateField(blank=True, null=True, verbose_name='サービス終了日')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_service_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lancers_service_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'サービス',
                'verbose_name_plural': 'サービス',
            },
        ),
    ]
