# Generated by Django 2.2.16 on 2021-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0019_auto_20210307_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylevel',
            name='memo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
    ]
