# Generated by Django 2.2.16 on 2021-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancers', '0020_categorylevel_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='attitude',
            field=models.IntegerField(blank=True, choices=[(1, '1. 横暴'), (2, '2. 普通'), (3, '3. 丁寧')], null=True, verbose_name='態度'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='目的'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='その他メモ'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(3, '3. 頻繁'), (2, '2. 普通'), (1, '1. 少ない')], null=True, verbose_name='連絡頻度'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='level_comprehensive',
            field=models.IntegerField(blank=True, choices=[(3, '3. 高い'), (2, '2. 普通'), (1, '1. 低い')], null=True, verbose_name='技術レベル'),
        ),
    ]
