# Generated by Django 2.2.9 on 2020-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200105_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
