# Generated by Django 2.2.9 on 2020-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200214_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_nisa',
            field=models.BooleanField(default=False, verbose_name='NISA'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_plan',
            field=models.BooleanField(default=False, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
