# Generated by Django 2.2.9 on 2020-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200215_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
