# Generated by Django 2.2.9 on 2020-02-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200223_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V_Entry',
        ),
    ]
