# Generated by Django 2.2.9 on 2020-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_delete_v_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='num_plan',
            field=models.IntegerField(default=0, verbose_name='予定口数'),
        ),
    ]
