# Generated by Django 2.2.9 on 2020-03-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200305_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBIAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('val', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, '円以上'), (1, '円以下'), (2, '％以上'), (3, '％以下')])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Stock')),
            ],
        ),
    ]
