# Generated by Django 2.2.9 on 2020-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_entry_is_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_nisa',
            field=models.BooleanField(default=False, help_text='NISA口座', verbose_name='NISA'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_plan',
            field=models.BooleanField(default=False, help_text='Entry予定', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='シミュレーション', verbose_name='Simulation'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='num_plan',
            field=models.IntegerField(default=0, help_text='予定口数', verbose_name='予定口数'),
        ),
    ]
