# Generated by Django 2.2.9 on 2020-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_entry_val_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_plan',
            field=models.BooleanField(default=False, help_text='EntryPlanかどうか', verbose_name='EntryPlan'),
        ),
    ]
