# Generated by Django 2.2.9 on 2020-04-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200411_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=100)),
                ('min_profit_percent', models.FloatField(help_text='足切り利益率')),
                ('max_holding_period', models.IntegerField(help_text='最大保有期間')),
                ('is_within_week', models.BooleanField(help_text='週跨ぎしないEntry')),
                ('is_within_holding_period', models.BooleanField(default=True, help_text='保有期間超えを許容しない')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('短期', '短期'), ('中期', '中期'), ('長期', '長期')], default='中期', max_length=10, verbose_name='Entry種別'),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.EntryStatus'),
        ),
    ]
