# Generated by Django 2.2.9 on 2020-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200412_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrystatus',
            name='max_holding_period',
            field=models.IntegerField(blank=True, help_text='最大保有期間', null=True),
        ),
        migrations.AlterField(
            model_name='entrystatus',
            name='min_profit_percent',
            field=models.FloatField(blank=True, help_text='足切り利益率', null=True),
        ),
    ]
