# Generated by Django 2.2.9 on 2020-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200412_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrystatus',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('短期', '短期'), ('中期', '中期'), ('長期', '長期')], max_length=10, null=True, verbose_name='Entry種別'),
        ),
    ]
