# Generated by Django 2.2.9 on 2020-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200502_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='consolidated_business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='連結事業'),
        ),
        migrations.AddField(
            model_name='stock',
            name='feature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='特色'),
        ),
        migrations.AddField(
            model_name='stock',
            name='settlement_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='決算月'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='単元株数'),
        ),
    ]
