# Generated by Django 2.2.9 on 2020-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200503_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='num_plan',
            field=models.IntegerField(default=0, verbose_name='予定口数'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='val_plan',
            field=models.FloatField(blank=True, null=True, verbose_name='予定Entry株価'),
        ),
    ]
