# Generated by Django 2.2.9 on 2020-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200504_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='entrystatus',
            name='is_for_plan',
            field=models.BooleanField(default=False, help_text='Plan向けステータス'),
        ),
    ]
