# Generated by Django 2.2.9 on 2020-07-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200523_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dividend',
            field=models.IntegerField(blank=True, null=True, verbose_name='配当金'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True, verbose_name='配当利回り'),
        ),
    ]
