# Generated by Django 2.2.9 on 2020-07-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20200704_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('date', models.DateField(verbose_name='日付')),
                ('val_close_dy', models.FloatField(verbose_name='終値前日比')),
                ('val_close_dy_pct', models.FloatField(verbose_name='終値前日比率')),
                ('turnover_dy', models.FloatField(verbose_name='出来高前日比')),
                ('turnover_dy_pct', models.FloatField(verbose_name='出来高前日比率')),
                ('val_line', models.FloatField(verbose_name='ローソク長')),
                ('val_line_pct', models.FloatField(verbose_name='ローソク長率')),
                ('is_positive', models.BooleanField(verbose_name='陽線')),
                ('lower_mustache', models.FloatField(verbose_name='下ヒゲ')),
                ('upper_mustache', models.FloatField(verbose_name='上ヒゲ')),
                ('ma05', models.FloatField(verbose_name='移動平均（5日）')),
                ('ma25', models.FloatField(verbose_name='移動平均（25日）')),
                ('ma75', models.FloatField(verbose_name='移動平均（75日）')),
                ('ma05_diff', models.FloatField(help_text='終値ー5日移動平均', verbose_name='移動平均乖離（5日）')),
                ('ma25_diff', models.FloatField(help_text='終値ー25日移動平均', verbose_name='移動平均乖離（25日）')),
                ('ma75_diff', models.FloatField(help_text='終値ー75日移動平均', verbose_name='移動平均乖離（75日）')),
                ('ma05_diff_pct', models.FloatField(verbose_name='移動平均乖離率（5日）')),
                ('ma25_diff_pct', models.FloatField(verbose_name='移動平均乖離率（25日）')),
                ('ma75_diff_pct', models.FloatField(verbose_name='移動平均乖離率（75日）')),
                ('sigma25', models.FloatField(verbose_name='標準偏差（25日）')),
                ('ma25_p2sigma', models.FloatField(verbose_name='ボリンジャーバンド+2σ（25日）')),
                ('ma25_m2sigma', models.FloatField(verbose_name='ボリンジャーバンド-2σ（25日）')),
                ('is_upper05', models.BooleanField(help_text='前日移動平均値より上（5日）', verbose_name='上昇傾向（5日）')),
                ('is_upper25', models.BooleanField(help_text='前日移動平均値より上（25日）', verbose_name='上昇傾向（25日）')),
                ('is_upper75', models.BooleanField(help_text='前日移動平均値より上（75日）', verbose_name='上昇傾向（75日）')),
                ('is_takuri', models.BooleanField(help_text='長い下ヒゲ陰線', verbose_name='たくり線')),
                ('is_tsutsumi', models.BooleanField(help_text='前日ローソクを包み込む、大きいローソク', verbose_name='包線')),
                ('is_harami', models.BooleanField(help_text='前日ローソクに包まれる、小さいローソク', verbose_name='はらみ線')),
                ('is_age_sanpo', models.BooleanField(help_text='大陽線後→3本のローソクが収まる→最初の陽線終値をブレイク', verbose_name='上げ三法')),
                ('is_sage_sanpo', models.BooleanField(help_text='大陰線後→3本のローソクが収まる→最初の陰線終値を割り込み', verbose_name='下げ三法')),
                ('is_sanku_tatakikomi', models.BooleanField(help_text='3日連続の窓開き下落', verbose_name='三空叩き込み')),
                ('is_sante_daiinsen', models.BooleanField(help_text='3日連続の大陰線', verbose_name='三手大陰線')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Stock')),
            ],
        ),
    ]
