# Generated by Django 2.2.9 on 2020-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_stockanalysisdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_age_sanpo',
            field=models.BooleanField(default=False, help_text='大陽線後→3本のローソクが収まる→最初の陽線終値をブレイク', verbose_name='上げ三法'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_harami',
            field=models.BooleanField(default=False, help_text='前日ローソクに包まれる、小さいローソク', verbose_name='はらみ線'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_sage_sanpo',
            field=models.BooleanField(default=False, help_text='大陰線後→3本のローソクが収まる→最初の陰線終値を割り込み', verbose_name='下げ三法'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_sanku_tatakikomi',
            field=models.BooleanField(default=False, help_text='3日連続の窓開き下落', verbose_name='三空叩き込み'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_sante_daiinsen',
            field=models.BooleanField(default=False, help_text='3日連続の大陰線', verbose_name='三手大陰線'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_takuri',
            field=models.BooleanField(default=False, help_text='長い下ヒゲ陰線', verbose_name='たくり線'),
        ),
        migrations.AlterField(
            model_name='stockanalysisdata',
            name='is_tsutsumi',
            field=models.BooleanField(default=False, help_text='前日ローソクを包み込む、大きいローソク', verbose_name='包線'),
        ),
    ]
