# Generated by Django 2.2.9 on 2020-09-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200718_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysisdata',
            name='svd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.StockValueData', verbose_name='SVD'),
        ),
    ]
