# Generated by Django 2.2.16 on 2020-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_stockanalysisdata_svd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('date', models.DateField(verbose_name='日付')),
                ('val_investment', models.IntegerField(verbose_name='予定投資元本')),
                ('val_target', models.IntegerField(verbose_name='投資目標')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
    ]
