# Generated by Django 2.2.24 on 2021-07-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_assettarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_trust',
            field=models.BooleanField(default=False, verbose_name='投資信託'),
        ),
        migrations.CreateModel(
            name='Ipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('datetime_open', models.DateTimeField(blank=True, null=True, verbose_name='ブックビル開始日時')),
                ('datetime_close', models.DateTimeField(blank=True, null=True, verbose_name='ブックビル開始日時')),
                ('status', models.CharField(choices=[('0.起票', '0.起票'), ('1.評価中', '1.評価中'), ('2.申込済', '2.申込済'), ('3.落選（上場前）', '3.落選（上場前）'), ('3.当選（上場前）', '3.当選（上場前）'), ('4.落選（上場後）', '4.落選（上場後）'), ('4.当選（上場後）', '4.当選（上場後）')], default='0.起票', max_length=255, verbose_name='ステータス')),
                ('val_list', models.FloatField(blank=True, null=True, verbose_name='発行価格')),
                ('date_list', models.DateField(blank=True, null=True, verbose_name='上場日')),
                ('datetime_select', models.DateTimeField(blank=True, null=True, verbose_name='抽選開始日時')),
                ('is_applied', models.BooleanField(default=False, verbose_name='申込済')),
                ('date_applied', models.DateField(blank=True, null=True, verbose_name='申込日')),
                ('num_applied', models.IntegerField(blank=True, null=True, verbose_name='申込数')),
                ('point', models.IntegerField(blank=True, default=None, null=True, verbose_name='使用ポイント数')),
                ('result_select', models.CharField(blank=True, default='抽選待ち', max_length=255, null=True, verbose_name='抽選結果')),
                ('datetime_purchase_open', models.DateTimeField(blank=True, null=True, verbose_name='購入意思表示開始日時')),
                ('datetime_purchase_close', models.DateTimeField(blank=True, null=True, verbose_name='購入意思表示終了日時')),
                ('result_buy', models.CharField(blank=True, max_length=255, null=True, verbose_name='購入結果')),
                ('num_select', models.IntegerField(blank=True, null=True, verbose_name='当選数')),
                ('rank', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='評価')),
                ('val_predicted', models.FloatField(blank=True, null=True, verbose_name='予想初値')),
                ('url', models.URLField(blank=True, null=True, verbose_name='評価詳細URL')),
                ('val_initial', models.FloatField(blank=True, null=True, verbose_name='上場後初値')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Entry', verbose_name='Entry')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Stock', verbose_name='銘柄')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPO',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='配当日')),
                ('val_unit', models.IntegerField(verbose_name='配当単価')),
                ('unit', models.IntegerField(verbose_name='配当単位数')),
                ('val', models.IntegerField(verbose_name='配当総額（税引前）')),
                ('tax', models.IntegerField(verbose_name='税額')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Entry', verbose_name='Entry')),
            ],
            options={
                'verbose_name': '配当',
                'verbose_name_plural': '配当',
            },
        ),
    ]
