# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='current_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
