# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='kakeibo.Cards'),
        ),
    ]
