# Generated by Django 2.0.6 on 2018-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='credititems',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='credititems',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='kakeibo.Cards'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='credit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kakeibo.CreditItems'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='move_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_from', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='move_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_to', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='sharedkakeibos',
            name='move_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='sharedkakeibos',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='usageresourcerelations',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='usageresourcerelations',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='usages',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.Colors'),
        ),
    ]
