# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_resources_current_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
