# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20180422_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedkakeibos',
            old_name='is_expense',
            new_name='is_settled',
        ),
        migrations.AddField(
            model_name='sharedkakeibos',
            name='way',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
