# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-24 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_credits_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='current_val',
        ),
    ]
