# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20180423_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedkakeibos',
            name='move_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Resources'),
        ),
    ]
