# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_remove_resources_current_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='is_saving',
            field=models.BooleanField(default=False),
        ),
    ]
