# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-10 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_resources_is_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='usages',
            name='memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 10)),
        ),
        migrations.AlterField(
            model_name='sharedkakeibos',
            name='is_settled',
            field=models.BooleanField(default=True),
        ),
    ]
