# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_auto_20180525_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='credititems',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Colors'),
        ),
        migrations.AlterField(
            model_name='usages',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Colors'),
        ),
    ]
