# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-02 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_auto_20190210_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronKakeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('way', models.CharField(max_length=20)),
                ('move_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_from_cron', to='kakeibo.Resources')),
                ('move_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_to_cron', to='kakeibo.Resources')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages')),
            ],
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 2, 0, 1, 58, 230401, tzinfo=utc)),
        ),
    ]
