# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-07 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_auto_20190302_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('way', models.CharField(max_length=20)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_by', models.CharField(max_length=20)),
                ('move_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Resources')),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages')),
            ],
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 7, 11, 27, 15, 137189, tzinfo=utc)),
        ),
    ]
