# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-20 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0008_auto_20190407_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 20, 14, 10, 48, 891730, tzinfo=utc)),
        ),
    ]
