# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-21 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0009_auto_20190420_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 21, 1, 29, 44, 523115, tzinfo=utc)),
        ),
    ]
