# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0011_auto_20190421_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 6, 15, 7, 854747, tzinfo=utc)),
        ),
    ]
