# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0012_auto_20190510_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 6, 20, 21, 322693, tzinfo=utc)),
        ),
    ]
