# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0013_auto_20190510_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
