# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0015_usualrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronkakeibo',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
