# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0016_cronkakeibo_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='kakeibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Kakeibos'),
        ),
    ]
