# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0018_auto_20190610_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usualrecord',
            name='way',
            field=models.CharField(choices=[('支出（現金）', '支出（現金）'), ('支出（クレジット）', '支出（クレジット）'), ('支出（Suica）', '支出（Suica）'), ('引き落とし', '引き落とし'), ('収入', '収入'), ('振替', '振替')], max_length=20),
        ),
    ]
