# Generated by Django 2.2.9 on 2020-01-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0019_auto_20190610_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
