# Generated by Django 2.2.9 on 2020-01-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0022_auto_20200128_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibos',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_kakeibo', to='kakeibo.Event'),
        ),
    ]
