# Generated by Django 2.2.9 on 2020-02-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0024_auto_20200202_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronkakeibo',
            name='move_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_from_cron', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='cronkakeibo',
            name='move_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_to_cron', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='cronkakeibo',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='cronshared',
            name='move_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='cronshared',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='event',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_kakeibo', to='kakeibo.Event'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='move_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_from', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='move_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_to', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='kakeibos',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='sharedkakeibos',
            name='move_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='sharedkakeibos',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages'),
        ),
        migrations.AlterField(
            model_name='usualrecord',
            name='move_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ur_move_from', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='usualrecord',
            name='move_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ur_move_to', to='kakeibo.Resources'),
        ),
        migrations.AlterField(
            model_name='usualrecord',
            name='usage',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.Usages'),
        ),
    ]
