# Generated by Django 2.2.9 on 2020-02-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0025_auto_20200202_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sum_plan',
            field=models.IntegerField(default=0),
        ),
    ]
