# Generated by Django 2.2.9 on 2020-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0026_event_sum_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True)),
                ('takashi', models.IntegerField()),
                ('hoko', models.IntegerField()),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
