# Generated by Django 2.2.9 on 2020-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0027_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
