# Generated by Django 2.2.9 on 2020-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0028_auto_20200224_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('val', models.IntegerField()),
                ('type', models.CharField(choices=[('総資産目標', '総資産目標'), ('投資目標', '投資目標')], max_length=20)),
                ('memo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='is_investment',
            field=models.BooleanField(default=False, help_text='投資用口座'),
        ),
        migrations.AddField(
            model_name='usages',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesomeのHTMLタグ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='is_saving',
            field=models.BooleanField(default=False, help_text='投資を除く貯金用口座'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='DataStudioで可視化'),
        ),
    ]
