# Generated by Django 2.2.9 on 2020-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0029_auto_20200426_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
