# Generated by Django 2.2.9 on 2020-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0030_auto_20200427_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='event',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メモ'),
        ),
    ]
