# Generated by Django 2.2.9 on 2020-08-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0031_auto_20200509_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30, verbose_name='イベント名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sum_plan',
            field=models.IntegerField(default=0, verbose_name='計画値'),
        ),
    ]
