# Generated by Django 2.2.9 on 2020-08-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0032_auto_20200808_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usualrecord',
            name='way',
            field=models.CharField(max_length=20),
        ),
    ]
