# Generated by Django 2.2.9 on 2020-09-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0033_auto_20200812_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('総資産目標', '総資産目標'), ('投資目標', '投資目標'), ('投資元本', '投資元本')], max_length=20),
        ),
    ]
