# Generated by Django 2.2.16 on 2021-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0034_auto_20200902_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usages',
            name='is_shared',
            field=models.BooleanField(default=True, verbose_name='共通家計簿で利用'),
        ),
        migrations.AlterField(
            model_name='usages',
            name='is_expense',
            field=models.BooleanField(verbose_name='支出'),
        ),
    ]
