# Generated by Django 2.2.24 on 2021-08-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0035_auto_20210307_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakeibos',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨'),
        ),
        migrations.AddField(
            model_name='kakeibos',
            name='fee_converted',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額（換算後）'),
        ),
        migrations.AddField(
            model_name='kakeibos',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='レート'),
        ),
    ]
