# Generated by Django 2.2.24 on 2021-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0036_auto_20210801_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibos',
            name='fee',
            field=models.FloatField(),
        ),
    ]
