# Generated by Django 2.2.24 on 2021-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0038_auto_20211018_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibos',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='通貨'),
        ),
    ]
