# Generated by Django 2.2.24 on 2021-10-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0039_auto_20211018_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronkakeibo',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='通貨'),
        ),
    ]
