# Generated by Django 2.2.24 on 2021-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0040_cronkakeibo_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usualrecord',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='cronkakeibo',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨'),
        ),
    ]
