name: Test and Deploy 

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, ]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Migrations # run migrations to create table in side car db container
      run: python3 manage.py migrate 
      env:
        SECRET_KEY: githubactions
        SENDGRID_API_KEY: a

    - name: Django app test
      run: python manage.py test 
      env:
        SECRET_KEY: githubactions
        SENDGRID_API_KEY: a

    - name: deploy
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_ADDR: ${{ secrets.SSH_ADDR }}
        SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
      run: |
        echo "${SECRET_KEY}" > secret_key
        chmod 600 secret_key
        ssh -oStrictHostKeyChecking=no ${SSH_USER}@${SSH_ADDR} -i secret_key "${SSH_COMMAND}"
