- name: deploy
  env:
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    SSH_USER: ${{ secrets.SSH_USER }}
    SSH_ADDR: ${{ secrets.SSH_ADDR }}
    SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
  run: |
    echo "$SECRET_KEY" > secret_key
    chmod 600 secret_key
    ssh -oStrictHostKeyChecking=no ${SSH_USER}@${SSH_ADDR} -i secret_key "$SSH_COMMAND"
