name: Test

on:
#   pull_request:
#     branches: [ production ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified:  
    - name: Prepare Env
      env:
        URL_SLACK_NAMS: ${{ secrets.URL_SLACK_NAMS }}
      run: |
        echo "TEST=test" > .env
        echo "TRELLO_KEY=1" >> .env
        echo "TRELLO_TOKEN=1" >> .env
        echo "GOLDPOINT_ID=1" >> .env
        echo "GOLDPOINT_PASSWORD=1" >> .env
        echo "CELERY_ENVIRONMENT=fmanage.settings" >> .env
        echo "URL_SLACK_NAMS=${URL_SLACK_NAMS}" >> .env
        echo "URL_LOG_GAS=''" >> .env
        echo "LANCERS_PASSWORD=1" >> .env
        echo "LANCERS_USER_ID=1" >> .env
        echo "DRF_TOKEN=1" >> .env
        echo "TWITTER_ACCESS_KEY='a'" >> .env
        echo "TWITTER_CONSUMER_SECRET='C'" >> .env
        echo "TWITTER_CONSUMER_KEY='C'" >> .env
        echo "TWITTER_ACCESS_SECRET='I'" >> .env
        echo "SBI_PASSWORD_ORDER='1'" >> .env
        echo "SBI_USER_ID='1'" >> .env
        echo "SBI_PASSWORD_LOGIN='1'" >> .env
        python3 --version
        pip3 --version
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt-get install python3-setuptools
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Django app test
      run: python3 manage.py test 
#     - name: slack - GitHub Actions Slack integration
#       # You may pin to the exact commit or the version.
#       # uses: act10ns/slack@e4e71685b9b239384b0f676a63c32367f59c2522
#       uses: act10ns/slack@v1.2.2
#       with:
#         # Specify success, failure, cancelled or a custom status.
#         status: success
#         # Report on the status of individual steps
#         steps: # optional
#         # Override default channel with different channel or username
#         channel: # optional
